"""add feedback column to projects

Revision ID: f9d68163f6de
Revises: a2ec8a7ad717
Create Date: 2026-08-08 22:02:33.841979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d68163f6de'
down_revision = 'a2ec8a7ad717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
